### PR TITLE
Rule 8 - going long or short

### PR DESCRIPTION
**Pull request by rknegjens**
Another game element: speculating on player scoring futures. I was a bit rushed with this one, so please feel free to propose changes. I've also been added the regulation of only one investment per player at a time that we could lift once we're more comfortable with this mechanism.

### CODE REVIEW

**Comment by rknegjens** [comment]
Rule adjusted so that player's can't "swing" their score by placing an investment in order to frustrate another player's investment at key moments. Player's only lose their investment at the moment of evaluation. It's still possible to drop your score by forfeiting an investment by placing a new one, but this will lose you points.

**Comment by RamonRB** [comment]
I think I like this game element. Can you give me an example on how an investment might go, and how it is scored? The way it is described is a bit abstract for me.

**Comment by rknegjens** [comment]
Sure. Here is an example pull request I could make as a player for `investments.md` right now (assuming rule already valid):

```markdown
Investor: Rob
Timestamp: 11-4-2020 19:50 UTC
Investment: 6 points
Target: RamonRB
Relative score: 16 / 14.4 = 1.11
Prediction: increases (long)
Evaluation: after rule 12
```

Now let's say at the end of rule 12 your new score is 25 (for whatever reason), and the average group score is 20.4. Your new relative score is 1.23, which has *increased* from 1.11. I speculated correctly. There have been 4 complete voting rounds (9, 10, 11, 12) as the current one (8) doesn't count. So I will be awarded an extra 6 * (4 / 5) = 4.8 = 4 points.

Had your score instead been 22 points, your relative score would have 1.08, which is a *decrease*. My speculation would be wrong. I would then immediately (at end of round 12) lose my investment of 6 points.

**Comment by akvadrako** [comment]
I'm not so convinced about this. Personally betting on relative scores
seems quite difficult and meta - who knows what'll happen with them.

It would be more fun to bet on external things, like a prediction
market, with matched buyers and sellers.

**Comment by roarandrock** [comment]
I had to read this like five times and still not sure if I understand it. But this game could use some more ways to make points. So why not.

**Review by roarandrock — APPROVED** [review]

**Comment by rknegjens** [comment]
> I'm not so convinced about this. Personally betting on relative scores
seems quite difficult and meta - who knows what'll happen with them.

I agree it's difficult but would argue that's part of the fun. It's also a catch up mechanic: if one person races ahead the others can place futures on their success to catch up. As we add other game elements it may also synergize well to speculate on game winners.

> It would be more fun to bet on external things, like a prediction
market, with matched buyers and sellers.

Not sure what you mean by _matched_? Isn't this just as difficult yet less gamey because we have zero influence on it? I agree it could be fun to track real world indexes etc, but which and how? Seems like a more involved rule?

**Comment by rknegjens** [comment]
> I had to read this like five times and still not sure if I understand it. But this game could use some more ways to make points. So why not.

Is there a part of rule I could improve? The general idea maybe?

**Comment by akvadrako** [comment]
On Mon, 2020-04-13 at 02:40 -0700, Rob Knegjens wrote:
> 
> Not sure what you mean by matched?

I mean like a real market, with buyers and sellers agreeing on terms.

**Comment by akvadrako** [comment]
Since I don't think I would use this rule myself and I think a different market formulation would be better, I can't in good conscience approve this.

So I vote **reject**.

**Comment by roarandrock** [comment]
So can we close this and move on to the next rule proposal?

**Comment by akvadrako** [comment]
> So can we close this and move on to the next rule proposal?

Ramon and fpug still need to vote.

**Comment by RamonRB** [comment]
Again, I've been neglecting my duties in this game. My apologies. I will approve this request, as it doesn't seem to complex to me and it gives more game possibilities.

**Review by RamonRB — APPROVED** [review]

**Comment by akvadrako** [comment]
Thanks Ramon. I guess @fpug is not going to vote, so I think we can close this and move on. I'll do scoring a bit later.

**Pull request closed without merging**
