### PR TITLE
Rule 307 - The 'Fruits' side game

### PR DESCRIPTION
**Pull request by RamonRB**
I thought it might be fun to add a little whimsy

### CODE REVIEW

**Comment by akvadrako** [comment]
Looks fun, and it's mostly orthogonal to other concerns, so low risk. One question and one suggestion:

- If rule 307 is repealed, does that immediately trigger the 50 point payout? Does it pre-empt a repeal?
- I suggest rule 307 is self-auto-repealed after it's concluded, so someone doesn't need to clean it up afterwards.

**Comment by roarandrock** [comment]
I don't like taking selfies. But I do like whimsy. I'll vote to approve if you add the suggestion from Drako and clarify that 50 points are NOT awarded by a repeal. 50 points should only be awarded by completing the minigame.

**Comment by rknegjens** [comment]
I like the game aspect and don't mind purchasing and photographing (exotic) fruits, but I don't like the selfie element so much (+ repo is public). Perhaps that element could be made optional and we can ensure authenticity of the photo taken another way e.g. the photo must contain an in-photo (non-photoshopped) reference to the rule # being proposed. Also photo could be encouraged to set the theme of the rule e.g. for previous rule Dev could've dressed up a pineapple as a policeman:p

**Comment by RamonRB** [comment]
The idea of still receiving points when repealed is that it won't make the effort put in for making pictures pointless. Otherwise people may have spent weeks taking selfies, with no payout if someone repeals is. Also, it might make some meta gaming possible on when to repeal it, if you don't want a particular person getting the points (e.g. they are about to win), but wouldn't mind so much if someone else gets them.

I'm OK with no selfies, as I'm not particularly fond of them myself, and I also didn't release the repo was public. I like Rob's idea to take the photo with the rule being proposed.

**Comment by rknegjens** [comment]
I share the sentiment that the harkwork of taking photos and buying fruit should be rewarded, but a repeal is the majority deciding at a later date that it shouldn't i.e. not sharing that sentiment, which should stay possible (amend is also possible). If we want to protect the rule against repealwe can vote to transmute it to immutable.

If you're happy keeping repeal of entire rule possible and change selfie to inclusion of rule number in photo, then I will vote in favour!

**Review by akvadrako — APPROVED** [review]

**Comment by rknegjens** [comment]
@RamonRB will you change the rule as proposed? If not I will vote.

**Comment by rknegjens** [comment]
Note that everyone except RamonRB has lost a 1 VK for being a day late in voting/discussion duties (these comments now reset the timer).

**Comment by fpug** [comment]
Noooo

**Comment by fpug** [comment]
I'm against selfies, camera on the phone is not very serviceable, transferring pictures from there a pain in the ass.  Nope, nope, nope.

**Comment by roarandrock** [comment]
@rknegjens doesn't @akvadrako  not lose VK since he approved within 24 hours of the last discussion?

**Comment by roarandrock** [comment]
And in the interest of time I'm going to hit approve. The next person can propose any modifications they want for us to vote on.

**Review by roarandrock — APPROVED** [review]

**Comment by akvadrako** [comment]
> @rknegjens doesn't @akvadrako not lose VK since he approved within 24 hours of the last discussion?

Actually Rob is correct:

The last comment was on 5 April, so the timer starts on 6 April 00:00. My vote was on 7 April 17:00. Rounded to the nearest 24 hours, I am 24 hours late, so I lose 1 VK.

Then Rob  replies to himself, that doesn't reset the timer. Nor does my vote.

The next relevant comment is fpug on 8 April 10:00. This resets the timer, meaning we all lose 1 VK.

So make sure you vote or continue the conversation before 9 April 12:00 (UTC) or lose another VK.

**Comment by akvadrako** [comment]
> Noooo

Does this count as a no vote?

**Comment by rknegjens** [comment]
As rule was not amended as discussed above I will (also in interest of time) vote no.

**Review by rknegjens — COMMENTED** [review]
No vote

**Comment by akvadrako** [comment]
I think we can say based now it's 3 for, 2 against. I'll do scoring in a minute, one last thing for @RamonRB: do you want to change your class?

**Comment by akvadrako** [comment]
Ramon gets 1VK and (307-291) × ⅗ × ½ = 5 points, we all lose 1VK.

The score is calculated by rule 202, part 2:

> subtract 291 from the ordinal number of their proposal and multiply the result by the fraction of favorable votes it received, rounded to the nearest integer. (This yields a number between 0 and 10 for the first player

and new rule 304:

> When a proposed rule-change is defeated, the player who proposed it shall subtract half of the points (rounded down to the nearest integer) he or she is about to gain in part (2) of the turn from his or her score.

**Comment by RamonRB** [comment]
I'm sorry I have been off the grid the last few days. Work was extremely busy and I kind of forgot tbh. I would amend this rule, but I believe we are still in the phase where rules need to pass unanimously, correct? So with one resolute no (and I believe no chance of changing his mind) there would be not much use to.

**Comment by RamonRB** [comment]
Also, I like to change my class to policeman

**Comment by akvadrako** [comment]
done

**Pull request closed without merging**
