### PR TITLE
Rule 311

### PR DESCRIPTION
**Pull request by RamonRB**
The idea behind this rule is to add a ticking clock to the game, as well as encouraging speedy discussion and voting. It can also be used for tactical fillibustering, modeling actual politics. Because rules now only need a simple majority to pass or fail, it will not be possible for one person to misuse this rule by stalling indefinitely to secure his or her victory.

### CODE REVIEW

**Comment by RamonRB** [comment]
Also, as the Police I would like to point out the following errors in the file class.md:

* Lobbyist is written with three b's
* The line 'He may also offer other players some of this points ' should read 'these points'
* 'mispelling' in the section for the Police should read 'misspelling'

And the following error in the file readme.md:

* The line 'Classes gives specific players' should read 'classes give specific players'

**Comment by roarandrock** [comment]
Damn, I meant to police those. You beat me to it. But, point of clarification, do you get police points for typos in the "class.md" file? Or is it intended to only apply to typos in the rules? The class.md file is not a rule.

**Review by roarandrock — APPROVED** [review]

**Comment by roarandrock** [comment]
I vote to approve the rule. Sounds like a interesting way to speed things up

**Comment by RamonRB** [comment]
> Damn, I meant to police those. You beat me to it. But, point of clarification, do you get police points for typos in the "class.md" file? Or is it intended to only apply to typos in the rules? The class.md file is not a rule.

I would argue that the class.md is part of the rules, as without it you wouldn't be able to make use of rule 306. Also, the description of the class Police does not specify any limits on where the typos need to be present.

**Comment by akvadrako** [comment]
> I would argue that the class.md is part of the rules, as without it you wouldn't be able to make use of rule 306. Also, the description of the class Police does not specify any limits on where the typos need to be present.

Putting on my judges hat (rule 211), I have to say classes are not part of "the rules" because it says explicitly in rule 306: "Classes do not count as rules.". But Ramon is right that Police says "mispellings" in general, not restricting them to rules. Obviously there are some limits; I wouldn't say it can apply to comments, for example.

Thanks Ramon for your editing - I'll fix the Class file soon and give you 30 points.

I think this rule is interesting; it's simple and gives the game some urgency, so I'll approve.

**Review by akvadrako — APPROVED** [review]

**Comment by RamonRB** [comment]
> Obviously there are some limits; I wouldn't say it can apply to comments, for example.

I agree, although if you would read the description pedantically, you could argue that any typo whereever would count. This would mean that I would have won by now, as I'm sure I could find a misspelling or 2000 on Wikipedia.
But in the spirit of the game, I accept any of the md files on this git, and exclude the comments. A new rule change could set a new limit of course.

> Thanks Ramon for your editing - I'll fix the Class file soon and give you 30 points.
> 
Wouldn't that be 40? I pointed out 4 misspellings.

**Comment by akvadrako** [comment]
Yes, 40 points. Also (311-291)=20 for this rule. And 3 of us get 1 VK. I guess @rknegjens doesn't get one since he didn't participate :thinking: 

Also I've added the target points to the top of the README. Currently it's 200.

**Pull request merged**
