### PR TITLE
Rule 9 - Faster decision making

### PR DESCRIPTION
**Pull request by roarandrock**
Making it easier for the game to move faster. 

New text:
**203.** Voting for a rule-change is completed when one of these two conditions is met (if both conditions are true, then only the condition that happened first):
(1) The rule-change is approved by majority of players, rounding up (i.e. 3 players in a 5 player game, 2 players in a 4 player game). If this condition is met, then the rule change is adopted.
(2) The rule-change is rejected by majority of players, rounding up. If this condition is met, then the rule change is not adopted. 

Original text:
203. A rule-change is adopted if and only if the vote is unanimous among the eligible voters. If this rule is not amended by the end of the second complete circuit of turns, it automatically changes to require only a simple majority.

### CODE REVIEW

**Review by akvadrako — APPROVED** [review]
I like that you keep the majority rule improvement.

**Comment by RamonRB** [comment]
I agree with the idea for a quicker game, but 2 votes in a 4 player game, means that there only need to be 1 extra yes apart from the rule proposer. We need some sort of tie breaker system. Maybe the one with the highest Karma at that point can break the tie or some such. 

I will vote yes if something like that is amended to the rule.

**Comment by roarandrock** [comment]
Updated to address RamonRB's concerns. So for a 4 player game it requires 3 players. Karma points break a 2-2 tie.

**Review by RamonRB — APPROVED** [review]

**Comment by rknegjens** [comment]
I believe amending a rule still replaces it with a new rule number i.e. per rule 108:

> If a rule is amended or transmuted, it receives the number of the proposal to amend or transmute it.

**Comment by roarandrock** [comment]
You are correct @rknegjens 

Updated to be rule 309

**Review by rknegjens — APPROVED** [review]

**Comment by roarandrock** [comment]
I got votes from everyone but fpug. Since he's invoked rule 113, @akvadrako can you close this as successful and update the points?

**Comment by roarandrock** [comment]
Also, I'd like to change my class to Police

**Comment by akvadrako** [comment]
Scoring for rules 308 and 309:

@rknegjens gains (308-291) * 3/5 * 1/2 = 5.1
@roarandrock gains (309-291) = 18

Ramon's VK dropped to 0, then gained 1. Other players all gained 2.

Also because I'm the Buddha, at the beginning of my turn I gain my VK in points (4).

We now have 13 mutable rules, FYI.

**Pull request merged**
