### PR TITLE
rule 304 proposal

### PR DESCRIPTION
**Pull request by fpug**
Is this how this works?

### CODE REVIEW

**Comment by akvadrako** [comment]
I think we should do it a bit differently - if you are proposing a rule modification, you should just change that rule. This way the ruleset stays clear - it's always the current state. You (or I) can add the proposal to History.md to keep a record of what happened.

**Comment by rknegjens** [comment]
> I think we should do it a bit differently - if you are proposing a rule modification, you should just change that rule. This way the ruleset stays clear - it's always the current state. You (or I) can add the proposal to History.md to keep a record of what happened.

According to 108 an amended rule adopts new rule number, so we should then move the amended rule down, modify and renumber

**Comment by rknegjens** [comment]
We will be successively receiving more points as game progresses independent of how vote goes, and with 204 repealed 206 is currently only rule that swings the score. If we decide to keep it, perhaps better to make it proportional of points proposer will earn that round. e.g. 50% penalty

**Comment by roarandrock** [comment]
What is the goal of this change? It seems like a limited impact.

**Comment by fpug** [comment]
The goal is to keep the game flowing, since I was delaying a bit.
It has intentionally limited impact.

**Comment by fpug** [comment]
I like the idea of keeping it proportional, however we would have to agree on rounding - or consider half points.  This will in fact increase the absolute penalty for not getting a rule approved over the course of the game.

**Comment by roarandrock** [comment]
Proportional, rounded down is my suggestion. Half points are annoying. I'd vote to pass that

**Comment by rknegjens** [comment]
I second that: would vote for proportional, rounded up or down ok. If you make that change (via commit), I will vote. I like that in the first rounds it's less of a penalty for failing a vote, while after ~7 turns it will become a stronger penalty.

By not making it 100% we essentially keep a timer on the game, as it's first to 200 points and every round we all go up in points regardless of what happened.  Not saying game needs a timer, but useful in absence of other scoring mechanisms.

**Comment by RamonRB** [comment]
I agree that the amount should be proportional, as 10 rounds from now a 5 point penalty will be trivial. With that change, I will vote to approve.

**Comment by fpug** [comment]
Amended!

**Review by akvadrako — APPROVED** [review]

**Review by rknegjens — APPROVED** [review]

**Review by roarandrock — APPROVED** [review]

**Review by RamonRB — APPROVED** [review]

**Pull request merged**
