### PR TITLE
306 - Get some class

### PR DESCRIPTION
**Pull request by akvadrako**
I think it's time to start making the game more fun by giving it some thematic elements. Therefor I am introducing classes, which are like player-specific rules.

Another reason I think classes are a good idea is so we can experiment with rule variations without applying them to everybody.

I have included a starting list of classes, but I expect even if you like the idea in general, you may have concerns with specific classes. That's fine - please let me know in the comments.

### CODE REVIEW

**Comment by RamonRB** [comment]
I like the general idea, but I'm confused on the Buddha. What do his abilities do exactly? Escpecially the words of Wisdom.

Also, how does one become a different class than Peasant at this time?

**Comment by akvadrako** [comment]
> I like the general idea, but I'm confused on the Buddha. What do his abilities do exactly? Escpecially the words of Wisdom.

Words of wisdom don't have any force, but they are prominently displayed. He can play a bit differently - basically instead of adding rules he can sit back and gain VK. His total VK is added to his points each round, so earning more karma is his goal.

> Also, how does one become a different class than Peasant at this time?

As written, you need to choose a class on a successful proposal. If people want, we can allow a one time choice right now.

**Comment by RamonRB** [comment]
> As written, you need to choose a class on a successful proposal. If people want, we can allow a one time choice right now.

Wouldn't that mean that if people would disagree with the chosen class, but agree with the rule in general, that they might vote against?

**Comment by akvadrako** [comment]
> > As written, you need to choose a class on a successful proposal. If people want, we can allow a one time choice right now.
> 
> Wouldn't that mean that if people would disagree with the chosen class, but agree with the rule in general, that they might vote against?

I suppose so, yes. Perhaps it's better that the class change is applied even if the proposal is rejected. The reason I want to make it part of the proposal is to simplify the workflow. Each turn you make one proposal and it includes everything necessary.

But it's already the case that failed proposals require some changes - getting partial points.

**Comment by roarandrock** [comment]
I like the concept. But I don't like the change-class as a side-action. Seem loose, needs more definition. Can you pick any of the classes? Are there limitations on how many players can be each class? I propose that if a player chooses to change class the new class is picked randomly.

**Comment by akvadrako** [comment]
> I like the concept. But I don't like the change-class as a side-
> action. Seem loose, needs more definition. Can you pick any of the
> classes? Are there limitations on how many players can be each class?
> I propose that if a player chooses to change class the new class is
> picked randomly.

Yes, you can pick any of the classes. There is no limit of players per
class.

Mechanically, how it will work is that your proposal will include a
rule change plus optionally one of:

- change the class of your user (I need to add it to the list of
players)
- make an allowed change in the Class.md file

I realize this is a big change, so I'm open to compromise. It can be
random, but I think it's nicer if people can choose.

**Comment by rknegjens** [comment]
I also like the idea but have same concern about tying class change to vote, as this will bias voting.

I think all of the classes are interesting (nice job!) but some seem a bit OP, eg president or squirrel. Perhaps they need stronger downsides, or a more variable or tunable mechanic. We could break this idea into multiple rules as I intended for VK eg first decide on having classes, starting with two that have clear trade off, and then later vote to introduce each new class iteratively

**Comment by akvadrako** [comment]
I have made a few changes. (1) now updating Class.md can only be done instead of a normal rule mutation - it's not a side action. (2) at the end of one's turn, one can change their class. This happens after voting and points are updated. (3) I removed squirrel and president classes (for now).

**Review by roarandrock — APPROVED** [review]

**Comment by roarandrock** [comment]
Let's give it a go

**Comment by fpug** [comment]
>  - Proposals that affect the class list may not also add or amend a rule, unless it's the *null rule*.

I don't have this clear.  A proposal must affect a rule, according to the rules.

**Comment by akvadrako** [comment]
> > * Proposals that affect the class list may not also add or amend a rule, unless it's the _null rule_.
> 
> I don't have this clear. A proposal must affect a rule, according to the rules.

I have changed the wording in the latest version:

- Instead of effectively mutating the rule list, a player may add, remove or amend a class. They
  do this formally by proposing the *null rule* and patching the *Class.md* file. The proposal
  will be voted on as normally done for rule changes.
- The *null rule* is "This rule has no effect and is immediately repealed."

So, it does formally affect a rule, it just doesn't have much power. There are other ways we could do it, like make a rule that says "use the class list version X".

**Comment by fpug** [comment]
oh I see!!  well, let's see!  greenlight from me!

**Review by fpug — APPROVED** [review]

**Comment by rknegjens** [comment]
Police still seems a bit OP, but let's live and learn!

**Review by rknegjens — APPROVED** [review]

**Review by RamonRB — APPROVED** [review]

**Comment by akvadrako** [comment]
And I hereby change my class to **Buddha**.

If you guys wouldn't mind putting your proposal number in the title of your future PRs, that would be helpful.

**Pull request merged**
