### PR TITLE
#15 new classes and tweaks

### PR DESCRIPTION
**Pull request by roarandrock**
Adding new classes and changing a few little things

### CODE REVIEW

**Comment by RamonRB** [comment]
I was toying with the idea of adding more classes myself, so I support this change. However, I have a few questions:
- How do the Corrupt Cop and Police work together? When the Corrupt Cop proposes misspellings, but the Police catches them (before the rule is committed to git), does the Police get points? 
- How does the Dark Buddhist work if he wants to leech points from multiple players? Does he spend 2 points to leech 2 from each player, or does he need to spend 6 to leech 2 from each?
- I think the Necromancer is too powerful in a 4 player game. Maybe if we had more players.
- I don't know if I can support spending real money to gain points in this game. I realise that this is contrary to my earlier proposal for the fruit game, but this feels a bit like pay to win to me.

**Comment by roarandrock** [comment]
Updated with some tweaks:
1. Clarified how the Police can stop the Corrupt Cops
2. The Dark Buddha is one to one, so if he wants to remove one VK from three players it takes three VK of his own
3. I added some costs to being the necromancer. I think it's not too unbalanced because a Necromancer still couldn't stop or add new rules without the support of at least one other player. 
4. Added a homemade pizza option. And changed the point values so it's more VK and less actual points. It's not pay to win, it's win win. One player wins in points and the other in eating pizza.

**Comment by roarandrock** [comment]
In General I'm a fan of games where each class feels absurdly powerful for how they break the game. Also this game is almost over, so why not go a little mad?

**Comment by akvadrako** [comment]
I can't support the pizza guy. Tomorrow I could/will just send pizza to each of your houses, get 300VK, then start my turn and win.

**Comment by RamonRB** [comment]
I agree with akvadrako. I'm on board with all the roles, except for the pizza guy. Also, the end of the game can be very much in flux. There's no rule that says we can't change to win condition of the game.

**Comment by roarandrock** [comment]
Hmm. I'm open to suggestions. What's the most enticing reward to offer someone that will not give them the game but get me, who is losing this game horribly, some free pizza? 

I think you're both overvaluing how much any of us cares to win this game versus the real world cost and effort of ordering pizza. Yes, it's potentially overpowered, but would any of us actually do it more than once as a gag? 

Also @akvadrako , you can only have one class at a time right? And you can only switch your class after having a proposal voted on. So you'd have to switch to Pizza God. Then do the pizza shenanigans, then switch back to Buddhist before winning. You cannot take two turns in a row, so all we need to do is change something in the rules before you become a Buddhist again.

**Comment by akvadrako** [comment]
If a pizza happens to show up my door I'll take it as a sign from the pizza god that he should be surrected (the non-"re" form of resurrected).

**Comment by roarandrock** [comment]
The goal is that someone buys me pizza. 

In the interest of time, I'll reduce the reward for that second power.

**Comment by roarandrock** [comment]
I also capped it to three pizzas per day. Everybody happy?

**Review by akvadrako — APPROVED** [review]
Okay, I appreciate the effort and indeed it isn't trivial to take advantage of. So approve.

**Comment by RamonRB** [comment]
Agreed. Although I must admit that my initial read for having a pizza delivered to someone's house was 100 general points. Upon rereading I see that it is only VK. Now I think that 5 points is actually too few for the effort and cost of having something delivered to someone else. So I approve, and will even approve if you raise the points back to 10.

That said, I'm no great fan of pizza, so please do not deliver to my house :)

**Review by rknegjens — APPROVED** [review]

**Comment by rknegjens** [comment]
@RamonRB what's your address?;)

**Review by RamonRB — APPROVED** [review]

**Comment by roarandrock** [comment]
Thanks everyone. I’ll change my class to dark Buddhist.

**Comment by akvadrako** [comment]
points: 314 - 291 = 23

everyone gets 1 VK

**Pull request merged**
