### PR TITLE
rule 313

### PR DESCRIPTION
**Pull request by akvadrako**
> **313.** The first 3 players who approve this rule earn 50 extra points. The implied vote from the active player is counted first.

### CODE REVIEW

**Comment by akvadrako** [comment]
As Buddha I earn 7 points from my VK at the start of my turn.

**Comment by rknegjens** [comment]
This seems to unfairly target the slowest or most skeptical or critical player. I'm not sure I condone this type of play. What do others think?

**Comment by roarandrock** [comment]
I too think it is lame. And that it is not a rule but a thinly veiled attempt to cash in on his VK

**Comment by roarandrock** [comment]
I vote reject. There is no button for this it seems.

**Comment by RamonRB** [comment]
I don't mind some free extra points, and I think it's a clever idea, but I will only vote to approve if this rule is amended to specify that this type of rule can only be proposed once.

**Comment by akvadrako** [comment]
> I don't mind some free extra points, and I think it's a clever idea, but I will only vote to approve if this rule is amended to specify that this type of rule can only be proposed once.

Thanks for the support Ramon :) I have amended the proposal with this line:

> Players may not propose rules that immediately give themselves or other players extra points, for example this rule.

**Comment by rknegjens** [comment]
Thanks all for your comments. I too vote reject.

**Comment by akvadrako** [comment]
Technically, Ramon still needs to vote before I close this and do scoring.

**Comment by roarandrock** [comment]
Why do we need to wait? I thought the point of Rule 309 was that we could close a vote after two rejections?

**Comment by akvadrako** [comment]
Rule 309 defines a majority in a four player game as 3. Actually part 3 applies:

> (3) In case of a tie (i.e. 2 approve, 2 reject in a four player game) then karma points will be the tie breaker. Each side will tally their total karma points and the side with the largest sum of karma points will be considered the majority.

**Review by RamonRB — APPROVED** [review]
As promised, approved

**Comment by akvadrako** [comment]
Since Ramon and I have 8 VK vs Rob and Rob's 6 VK, it' approved ;)

Everybody gets 1VK, Ramon gets 50 points, @akvadrako gets 50 + (2/4) × (313-291) = 61 points.

**Pull request merged**
