### PR TITLE
Rule 312 proposal

### PR DESCRIPTION
**Pull request by rknegjens**
This is an amendment of rule 201.

### CODE REVIEW

**Comment by akvadrako** [comment]
In general I'm okay with it. Only I don't like how every other player loses VK if nothing is proposed - what if I proposed the rule before last but I want to give others a chance to submit something?

What if instead the player that proposes the next rule gains 2 VK if on time and 1 VK otherwise?  Everyone else doesn't lose it.

**Comment by rknegjens** [comment]
I didn't want to start also amending rule 303 by changing the karma penalty rules. We could make it that the player or players that haven't proposed a rule the longest suffer the penalty?

**Comment by roarandrock** [comment]
I agree with RK, we should all lose karma points if no one submits on time

**Comment by roarandrock** [comment]
What about the line that says we all have zero points? Does passing this mean we reset the scores? It would be a cheeky play

**Comment by rknegjens** [comment]
I find it tough what's the better way to enforce the karma penalty. If we always target the player who hasn't proposed the longest then they are given an incentive to participate, but it means that other players won't feel that incentive as much to keep game flowing.

@roarandrock regarding the zero points line, that was copied directly from rule 201. It refers to start of game. So nothing cheeky:)

**Review by akvadrako — APPROVED** [review]

**Review by roarandrock — APPROVED** [review]

**Review by RamonRB — APPROVED** [review]

**Comment by rknegjens** [comment]
@akvadrako I merged to master but did not yet updates the scores and VK.

As Lobbyist my score is updated by 3 * (312 - 291) * 2 = 126, taking it 17 + 126 = 143.
I was 4 days late, so my VK becomes 3 - 4 = -1

Points needed to win the game is 200 - 1 = 199

**Comment by akvadrako** [comment]
Damn, I forgot you're the Lobbyist - we should have demanded more favors :)

Anyway, you're scoring is off - you only get double the normal which is  `(312 - 291) × 2 = 42`.

**Comment by rknegjens** [comment]
Ah sorry, I missed the word 'fraction' in 'multiply the result by the fraction of favorable votes it received' :)

**Pull request merged**
